version: '3.2'

services:
  nginx:
    build:
      context: ./_docker/nginx
      dockerfile: Dockerfile
    volumes:
    - ./:/var/www
    environment:
      - "DB_HOST=mysql_db"
      - "XDG_CONFIG_HOME=/app"
    ports:
    - "8080:80"
    links:
      - php-fpm
      - node

  php-fpm:
    build:
      context: ./_docker/php-fpm
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
    environment:
      - "DB_HOST=mysql_db"
    links:
      - mysql_db
      - node

  php-cli:
    build:
      context: ./_docker/php-cli
      dockerfile: Dockerfile
    volumes:
    - ./:/var/www
    environment:
      - "DB_HOST=mysql_db"
      - "COMPOSER_MEMORY_LIMIT=-1"
    links:
      - mysql_db
    tty: true

  mysql_db:
    image: mysql:8.0
    restart: always
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: store_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 8101:3306
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    
  node:
    image: node:18-alpine
    ports:
        - "3000:3000"
    volumes:
    - ./:/var/www
    working_dir: /var/www
    tty: true

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    ports:
      - "1025:1025"
      - "8025:8025"

