version: '3.8'

services:
  nginx:
    build:
      context: ./_docker/nginx
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
      - product_images:/var/www/storage/app/product_images
    environment:
      - "DB_HOST=mysql_db"
    ports:
      - "8080:80"
    depends_on:
      - php-fpm
      - mysql_db
    networks:
      - app-network


  php-fpm:
    build:
      context: ./_docker/php-fpm
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
      - product_images:/var/www/storage/app/product_images
    environment:
      - "DB_HOST=mysql_db"
    depends_on:
      - mysql_db
      - node
      - redis
    networks:
      - app-network


  php-cli:
    build:
      context: ./_docker/php-cli
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
      - product_images:/var/www/storage/app/product_images
    environment:
      - "DB_HOST=mysql_db"
      - "COMPOSER_MEMORY_LIMIT=-1"
    depends_on:
      - mysql_db
      - redis
    tty: true
    networks:
      - app-network


  mysql_db:
    image: mysql:8.0
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: store_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_CHARSET: utf8
      MYSQL_COLLATION: utf8_unicode_ci
    ports:
      - 8101:3306
    networks:
      - app-network


  node:
    image: node:18-alpine
    ports:
      - "3000:3000"
    volumes:
      - ./:/var/www
    working_dir: /var/www
    tty: true
    networks:
      - app-network


  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - app-network

  
  redis:
    image: redis:alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    restart: unless-stopped
    networks:
      - app-network


  meilisearch:
    image: getmeili/meilisearch:v1.13
    ports:
      - "7700:7700"
    environment:
      MEILI_MASTER_KEY: '${MEILISEARCH_KEY}'
    volumes:
      - meilisearch_data:/data.ms
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
  meilisearch_data:
  redis_data:
  product_images: