version: '3.2'

services:
  nginx:
    build:
      context: ./_docker/nginx
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
      - ./storage/app/product_images:/var/www/storage/app/product_images 
    environment:
      - "DB_HOST=mysql_db"
      - "XDG_CONFIG_HOME=/app"
    ports:
      - "8080:80"
    links:
      - php-fpm
      - node

  php-fpm:
    build:
      context: ./_docker/php-fpm
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
      - ./storage/app/product_images:/var/www/storage/app/product_images 
    environment:
      - "DB_HOST=mysql_db"
    links:
      - mysql_db
      - node
      - redis

  php-cli:
    build:
      context: ./_docker/php-cli
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
      - ./storage/app/product_images:/var/www/storage/app/product_images 
    environment:
      - "DB_HOST=mysql_db"
      - "COMPOSER_MEMORY_LIMIT=-1"
    links:
      - mysql_db
      - redis
    tty: true

  mysql_db:
    image: mysql:8.0
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: store_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 8101:3306
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    
  node:
    image: node:18-alpine
    ports:
        - "3000:3000"
    volumes:
      - ./:/var/www
    working_dir: /var/www
    tty: true

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    ports:
      - "1025:1025"
      - "8025:8025"

  meilisearch:
    image: getmeili/meilisearch:v1.13
    ports:
      - "7700:7700"
    environment:
      MEILI_MASTER_KEY: I_K-pF9Sch-KZMf8B0PFJPjF3qFVut5nENzgh6PDt5w  # Ваш мастер-ключ
      MEILI_ENV: production 
    volumes:
      - meilisearch_data:/data.ms

  redis:
    image: redis:alpine
    command: redis-server --requirepass 1234
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=1234
    restart: unless-stopped
    networks:
      - default

volumes:
  mysql_data:
  meilisearch_data:
  redis_data: